import { Geist, Geist_Mono, Sora } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/Navbar";
import Ad from "./components/shared/Ad";
import Footer from "./components/shared/Footer";
import Logout from "./components/shared/Logout";
import Link from "next/link";
import { Toaster } from "react-hot-toast";
import Providers from "./providers";
import { AuthProvider } from "@/context/AuthContext";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata = {
  title: "PrintEra Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sora.className} antialiased `}>

        <AuthProvider>
          {children}
          <Toaster />
        </AuthProvider>

      </body>
    </html>
  );
}
